gestionale-laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WebsiteController@index');

// === resource crea tutte le routes e i relativi comandi HTTP
// === per gestire il CRUD
Route::resource('/anagrafica', 'AnagraficaController');

Route::get('/demo-ws-ajax', 'AnagraficaController@demo');

Route::get('/ws-ricerca-nominativo/{nome?}','WsAnagraficaController@ricercaNominativo');

gestionale-laravel/app/Anagrafica.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Anagrafica extends Model
{
    protected $table='anagrafica';
}

gestionale-laravel/app/Models/Anagrafica.php
<?php

/**
 * Created by Reliese Model.
 * Date: Sat, 01 Apr 2017 08:44:56 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Anagrafica
 * 
 * @property int $id
 * @property string $nome
 * @property string $cognome
 * @property string $email
 * @property int $tipo
 * @property string $foto
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * 
 * @property \Illuminate\Database\Eloquent\Collection $ordinis
 *
 * @package App\Models
 */
class Anagrafica extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;
	protected $table = 'anagrafica';

	protected $casts = [
		'tipo' => 'int'
	];

	protected $fillable = [
		'nome',
		'cognome',
		'email',
		'tipo',
		'foto'
	];

	public function ordinis()
	{
		return $this->hasMany(\App\Models\Ordini::class);
	}
}

gestionale-laravel/app/Http/Controllers/AnagraficaController.php
<?php

namespace App\Http\Controllers;

use App\Anagrafica;
use Illuminate\Http\Request;

class AnagraficaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // === Istanzio il model anagrafica
        $dati = new \App\Anagrafica();

        \Debugbar::addMessage('Benvenuti nel nostro applicativo', 'Welcome');
        \Debugbar::info($dati);


        return view('anagrafica.index')
                ->with([
                    //'anagrafica' => $dati::all()->toArray()     // --- Recupero TUTTI i record di Anagrafica
                    'anagrafica' => $dati::paginate(5)     // --- Recupero PAGINATI i record di Anagrafica
                ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('anagrafica.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // ==== Validazione dei dati  ====
        // make:request VerificaAnagraficaRequest
        // store(VerificaAnagraficaRequest $request)


        $anagrafica = new \App\Models\Anagrafica();

        $anagrafica->nome = $request->get('nome');
        $anagrafica->cognome = $request->get('cognome');
        $anagrafica->email = $request->get('email');
        $anagrafica->tipo = $request->get('tipo');

        // --- caso di default
        $anagrafica->foto = '';

        // === Meccanismo di gestione e caricamento file
        if(
           $request->hasFile('foto') && $request->get('foto')!=''
            && $request->file('foto')->isValid()
        )
        {
            // --- Recupero l'estensione del file caricato
            $extension = $request->foto->extension();
            $nomeFile = str_slug(
                        strtolower($request->get('nome').'-'.$request->get('cognome'))
                    ).'.'.$extension;

            $path = $request->foto->storeAs(
                'images',           // nome della cartella interna al disco
                $nomeFile,            // nome del file da caricare
                'uploads'           // nome del "disco" definito in config/filesystems.php
            );

            // === Popolo il campo della tabella
            $anagrafica->foto = $path;

        }

        $anagrafica->save();

        return redirect('/anagrafica');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Anagrafica  $anagrafica
     * @return \Illuminate\Http\Response
     */
    public function show(Anagrafica $anagrafica)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Anagrafica  $anagrafica
     * @return \Illuminate\Http\Response
     */
    public function edit(Anagrafica $anagrafica)
    {
        \Debugbar::disable();

        return view('anagrafica.edit')
                ->with(['anagrafica' => $anagrafica]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Anagrafica  $anagrafica
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Anagrafica $anagrafica)
    {
        $anagrafica->nome = $request->get('nome');
        $anagrafica->cognome = $request->get('cognome');
        $anagrafica->email = $request->get('email');
        $anagrafica->tipo = $request->get('tipo');
        $anagrafica->foto = '';

        $anagrafica->save();

        return view('anagrafica.index')->with([
            'msg' => 'Record Modificato ID='.$anagrafica->id
        ]);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Anagrafica  $anagrafica
     * @return \Illuminate\Http\Response
     */
    public function destroy(Anagrafica $anagrafica)
    {
        //
    }


    public function demo()
    {
        return view('anagrafica.demo');
    }
}

gestionale-laravel/resources/views/anagrafica/create.blade.php
@extends('layout.main-layout')

@section('mainContent')
    <div class="row">
        <h1>Gestione Anagrafica</h1>

        {{--
            Devo specificare:
            - metodo HTTP (default POST)
            - che viene effettuato upload del file
            - route name di destinazione
        --}}
        {!! Form::open(
                [
                    'route' => 'anagrafica.store',
                    'method' => 'POST',
                    'id' => 'frmInserisciNuovo',
                    'files' => true
                ]) !!}

            {{-- Elenco dei campi della maschera  --}}
            @include('includes.anagrafica-form')

        {!! Form::close() !!}

    </div>
@endsection

gestionale-laravel/resources/views/anagrafica/demo.blade.php
@extends('layout.main-layout')

@section('mainContent')
    <h1>Interrogazione del servizio</h1>

    <div id="result">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>nome</th>
                    <th>cognome</th>
                </tr>
            </thead>
            <tbody id="tableRow"></tbody>
        </table>
    </div>

@endsection


@section('scriptZone')
    <script>
        $(document).ready(function(){

            $.getJSON(
                '/ws-ricerca-nominativo?callback=?',
                function(result) {
                    console.log(result.data);

                    $(result.data).each(function(idx,item){

                        var tr = $('<tr>');
                        tr.attr('id', item.id);
                        tr.attr('class', 'rigo');

                        var out='';
                        out+='<td>'+item.id+'</td>';
                        out+='<td>'+item.nome+'</td>';
                        out+='<td>'+item.cognome+'</td>';

                        tr.html(out);

                        $('#tableRow').append(tr);

                    });

                    // === A tabella Renderizzata sul DOM, associo un eventListener al rigo
                    // === della tabella
                    $('.rigo').on('click',function () {
                        alert($(this).attr('id'));
                        $(this).fadeOut();
                    })


                }
            );


        });
    </script>

@endsection

gestionale-laravel/resources/views/anagrafica/edit.blade.php
@extends('layout.main-layout')

@section('mainContent')
    <div class="row">
        <h1>Gestione Anagrafica</h1>
        <h2>Modifica Record</h2>

        {{--
            Devo specificare:
            - metodo HTTP (default POST)
            - che viene effettuato upload del file
            - route name di destinazione
        --}}
        {!! Form::model(
                $anagrafica,
                [
                    'route' => ['anagrafica.update', $anagrafica->id],
                    'method' => 'PUT',
                    'id' => 'frmModificaAnagrafica',
                    'files' => true
                ]) !!}

        {{-- Elenco dei campi della maschera  --}}
        @include('includes.anagrafica-form')

        {!! Form::close() !!}

    </div>
@endsection

gestionale-laravel/resources/views/anagrafica/index.blade.php
@extends('layout.main-layout')

@section('mainContent')
    <div class="row">
        <h1>Gestione Anagrafica</h1>
        <a href="{!! route('anagrafica.create') !!}" class="btn btn-primary">Inserisci Nuovo</a>
    </div>

    {{-- Visualizzo messaggio di notifica --}}
    @if(isset($msg))
        <div class="row">
            <p class="bg-success">{{$msg}}</p>
        </div>
    @endif
<!--
<?php
print_r($anagrafica);
?>
-->
    {{-- Tabella HTML, Bootstrap compliant--}}
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Cognome</th>
                <th>Foto</th>
                <th>Action</th>
            </tr>
        </thead>


        <tbody>
        @foreach($anagrafica as $k => $item)
            <tr>
                <td>{{$item['id']}}</td>
                <td>{{$item['nome']}}</td>
                <td>{{$item['cognome']}}</td>
                <td>
                    @if(isset($item['foto']) && $item['foto']!=='')
                        <img src="/foto-caricate/{{$item['foto']}}"
                             alt="Foto di {{$item['nome']}} {{$item['cognome']}}"
                             width="100"
                                />
                    @else
                        <strong>Foto non disponibile</strong>
                    @endif
                </td>

                <!-- Action disponibili -->
                <td>
                    <!-- Mostra dettaglio record -->
                    {{link_to_route(
                        'anagrafica.show',              // nome del named-route
                        'Mostra',                       // testo del link
                        ['id' => $item['id']],          // array associativo con i parametri da passare
                        ['title' => 'Mostra dettaglio'] // attributi HTML custom
                        )}}
                    &nbsp;|&nbsp;

                    <!-- Modifica -->
                    {{link_to_route(
                        'anagrafica.edit',
                        'Modificat',
                        ['id' => $item['id']],
                        ['title' => 'Modifica Record']
                        )}}

                    &nbsp;|&nbsp;
                    <!-- Cancellazione -->
                    {{link_to_route(
                        'anagrafica.destroy',
                        'Elimina',
                        ['id' => $item['id']],
                        ['title' => 'Mostra dettaglio']
                        )}}

                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{-- Genera una struttura UL/LI/A Bootstrap compliant --}}
    {{$anagrafica->links()}}

    {{-- Visualizzazione tabella con PAGINAZIONE --}}
@endsection